"""Unit and Integration Tests for Voxel Lord: Feudal Realm Engine Vertical Slice.
Tests 3D chunk coordinate math, block taxonomy, Blender asset integrity,
Single Persistent Monarch vitals, and supply chain equilibrium.
"""

import unittest
import os
import math

class TestEngineVerticalSlice(unittest.TestCase):

    def setUp(self):
        self.project_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
        self.models_dir = os.path.join(self.project_dir, "assets", "models")
        self.scripts_dir = os.path.join(self.project_dir, "scripts")

    def test_chunk_volume_and_dimensions(self):
        """Verify 16x32x16 chunk standard."""
        chunk_x = 16
        chunk_y = 32
        chunk_z = 16
        total_blocks = chunk_x * chunk_y * chunk_z
        self.assertEqual(total_blocks, 8192)

    def test_chunk_coordinate_conversions(self):
        """Test world-to-chunk coordinate translation formulas."""
        def world_to_chunk(wx, wz):
            cx = math.floor(wx / 16.0)
            cz = math.floor(wz / 16.0)
            lx = wx - (cx * 16)
            lz = wz - (cz * 16)
            return (cx, cz), (lx, lz)

        # Inside origin chunk
        (cx, cz), (lx, lz) = world_to_chunk(5, 10)
        self.assertEqual((cx, cz), (0, 0))
        self.assertEqual((lx, lz), (5, 10))

        # Boundary coordinate
        (cx, cz), (lx, lz) = world_to_chunk(16, 32)
        self.assertEqual((cx, cz), (1, 2))
        self.assertEqual((lx, lz), (0, 0))

        # Negative coordinate
        (cx, cz), (lx, lz) = world_to_chunk(-1, -1)
        self.assertEqual((cx, cz), (-1, -1))
        self.assertEqual((lx, lz), (15, 15))

    def test_all_7_blender_glb_assets_exist_and_valid(self):
        """Verify all 7 low-poly 3D assets generated by headless Blender 5.2."""
        expected_assets = [
            "pickaxe.glb",
            "axe.glb",
            "sword.glb",
            "workbench.glb",
            "campfire.glb",
            "crate.glb",
            "citizen.glb"
        ]

        for asset in expected_assets:
            path = os.path.join(self.models_dir, asset)
            self.assertTrue(os.path.exists(path), f"Asset {asset} missing!")
            self.assertGreater(os.path.getsize(path), 1000, f"Asset {asset} has suspiciously small size!")
            
            # Verify GLB magic header
            with open(path, "rb") as f:
                magic = f.read(4)
                self.assertEqual(magic, b"glTF", f"Asset {asset} does not have valid glTF magic header!")

    def test_single_persistent_monarch_paradigm(self):
        """Verify Single Persistent Monarch respawn and lack of dynasty succession."""
        player_health = 0.0
        respawn_hearth = (32.0, 25.0, 32.0)
        
        # When health reaches 0, monarch respawns at castle hearth
        if player_health <= 0:
            player_health = 50.0 # Heals in infirmary
            current_pos = respawn_hearth
            has_dynasty_succession = False
            has_permadeath = False
            realm_persists = True

        self.assertEqual(player_health, 50.0)
        self.assertEqual(current_pos, (32.0, 25.0, 32.0))
        self.assertFalse(has_dynasty_succession)
        self.assertFalse(has_permadeath)
        self.assertTrue(realm_persists)

    def test_supply_chain_production_cycle(self):
        """Verify resource balance in supply chain calculations."""
        inventory = {
            "wheat": 20,
            "bread": 50,
            "logs": 30,
            "stone": 25,
            "iron_ore": 10,
            "tools": 10
        }
        assigned = {
            "farmer": 2,
            "baker": 1,
            "lumberjack": 2,
            "miner": 1
        }
        
        # 1. Farmers produce 4 wheat per farmer
        wheat_prod = assigned["farmer"] * 4
        inventory["wheat"] += wheat_prod
        
        # 2. Baker consumes up to 2 wheat to produce 4 bread
        wheat_needed = assigned["baker"] * 2
        wheat_used = min(inventory["wheat"], wheat_needed)
        inventory["wheat"] -= wheat_used
        inventory["bread"] += wheat_used * 2
        
        # 3. Citizens consume 1 bread each
        total_citizens = sum(assigned.values())
        bread_eaten = min(inventory["bread"], total_citizens)
        inventory["bread"] -= bread_eaten
        
        self.assertEqual(inventory["wheat"], 26) # 20 + 8 - 2 = 26
        self.assertEqual(inventory["bread"], 48) # 50 + 4 - 6 = 48
        self.assertGreater(inventory["bread"], 0)

    def test_3d_pathfinder_step_rules(self):
        """Verify 3D grid pathfinding step-up (1m) and drop (2m) constraints."""
        max_step_up = 1
        max_safe_drop = 2
        
        # Valid moves
        self.assertTrue(1 <= max_step_up)
        self.assertTrue(2 <= max_safe_drop)
        # Invalid moves
        self.assertFalse(2 <= max_step_up) # Cannot climb 2m vertical cliff without ladder
        self.assertFalse(3 <= max_safe_drop) # 3m fall causes injury

    def test_workstation_recipes_and_crafting_costs(self):
        """Verify blueprint recipes, cost consumption, and result outputs."""
        inventory = {"logs": 10, "stone": 20, "iron_ore": 6, "wheat": 6}

        # Craft Iron Pickaxe: cost 3 iron_ore, 1 log
        req_iron = 3
        req_log = 1
        self.assertGreaterEqual(inventory["iron_ore"], req_iron)
        self.assertGreaterEqual(inventory["logs"], req_log)

        inventory["iron_ore"] -= req_iron
        inventory["logs"] -= req_log
        crafted_item = {"name": "Iron Pickaxe", "type": "tool", "count": 1}

        self.assertEqual(inventory["iron_ore"], 3)
        self.assertEqual(inventory["logs"], 9)
        self.assertEqual(crafted_item["name"], "Iron Pickaxe")

    def test_farmland_tilling_mechanic(self):
        """Verify grass/dirt conversion to farmland via hoe."""
        BLOCK_GRASS = 2
        BLOCK_DIRT = 1
        BLOCK_FARMLAND = 13
        BLOCK_WHEAT_CROP = 14

        # Till grass
        current_block = BLOCK_GRASS
        if current_block in [BLOCK_GRASS, BLOCK_DIRT]:
            new_block = BLOCK_FARMLAND
        self.assertEqual(new_block, BLOCK_FARMLAND)

        # Plant wheat on farmland
        if new_block == BLOCK_FARMLAND:
            crop_block = BLOCK_WHEAT_CROP
        self.assertEqual(crop_block, BLOCK_WHEAT_CROP)

    def test_agriculture_hydration_and_growth_ticks(self):
        """Verify soil hydration radius, 2.2x speed boost, and 3-stage maturity."""
        hydration_radius = 4
        # Test water proximity
        water_pos = (30, 20, 30)
        farmland_pos_hydrated = (32, 20, 32)
        farmland_pos_dry = (40, 20, 40)
        
        dx = abs(farmland_pos_hydrated[0] - water_pos[0])
        dz = abs(farmland_pos_hydrated[2] - water_pos[2])
        is_hydrated = dx <= hydration_radius and dz <= hydration_radius
        self.assertTrue(is_hydrated)
        
        dx_dry = abs(farmland_pos_dry[0] - water_pos[0])
        self.assertFalse(dx_dry <= hydration_radius)

        # Growth simulation
        base_duration = 18.0
        # Dry crop
        dry_progress = (18.0 / base_duration) * 1.0 # 1.0 = 100%
        # Hydrated crop grows 2.2x faster
        hydrated_progress = (8.18 / base_duration) * 2.2 # reaches ~1.0 in ~8.2s
        self.assertGreaterEqual(dry_progress, 1.0)
        self.assertGreaterEqual(hydrated_progress, 0.99)

        # Harvest yield
        harvest_yield = {"wheat": 3, "seeds": 2}
        self.assertEqual(harvest_yield["wheat"], 3)
        self.assertEqual(harvest_yield["seeds"], 2)

    def test_threat_formula_scaling_and_raid_composition(self):
        """Verify GDD Threat calculation: 10 + (Pop * 1.5) + (StockpileValue * 0.05)."""
        pop = 6
        stockpile_val = 120.0
        threat_score = 10.0 + (pop * 1.5) + (stockpile_val * 0.05)
        self.assertAlmostEqual(threat_score, 25.0)

        # Bandit party size
        bandit_count = max(1, min(4, int(threat_score / 15.0)))
        self.assertEqual(bandit_count, 1)

        # Scaled kingdom with higher stockpile and pop
        big_pop = 20
        big_stockpile = 800.0
        big_threat = 10.0 + (big_pop * 1.5) + (big_stockpile * 0.05) # 10 + 30 + 40 = 80
        big_bandit_count = max(1, min(4, int(big_threat / 15.0)))
        self.assertEqual(big_bandit_count, 4)

    def test_bandit_combat_mechanics_and_loot(self):
        """Verify bandit raider stats, melee damage, and loot drop on defeat."""
        bandit_hp = 60.0
        sword_damage = 35.0
        axe_damage = 24.0

        # Player hits with sword
        bandit_hp -= sword_damage
        self.assertEqual(bandit_hp, 25.0)
        # Player hits with axe
        bandit_hp -= axe_damage
        self.assertEqual(bandit_hp, 1.0)
        # Final strike
        bandit_hp -= 16.0 # pickaxe
        self.assertLessEqual(bandit_hp, 0.0)

        # Defeated raider drops loot
        loot = {"iron_ore": 1, "coins": 5, "bread": 1}
        self.assertIn("iron_ore", loot)
        self.assertIn("coins", loot)
        self.assertGreater(loot["coins"], 0)

    def test_torch_lighting_flicker_simulation(self):
        """Verify torch light parameters and flicker energy range."""
        base_energy = 1.8
        flicker_speed = 12.0
        time_sec = 1.5
        flicker = math.sin(time_sec * flicker_speed) * 0.15 + math.cos(time_sec * flicker_speed * 1.7) * 0.1
        current_energy = base_energy + flicker
        self.assertGreaterEqual(current_energy, 1.55)
        self.assertLessEqual(current_energy, 2.05)

if __name__ == "__main__":
    unittest.main()
