"""Unit and Integration Tests for Voxel Lord: Feudal Realm Engine Vertical Slice.
Tests 3D chunk coordinate math, block taxonomy, Blender asset integrity,
Single Persistent Monarch vitals, and supply chain equilibrium.
"""

import unittest
import os
import math

class TestEngineVerticalSlice(unittest.TestCase):

    def setUp(self):
        self.project_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
        self.models_dir = os.path.join(self.project_dir, "assets", "models")
        self.scripts_dir = os.path.join(self.project_dir, "scripts")

    def test_chunk_volume_and_dimensions(self):
        """Verify 16x32x16 chunk standard."""
        chunk_x = 16
        chunk_y = 32
        chunk_z = 16
        total_blocks = chunk_x * chunk_y * chunk_z
        self.assertEqual(total_blocks, 8192)

    def test_chunk_coordinate_conversions(self):
        """Test world-to-chunk coordinate translation formulas."""
        def world_to_chunk(wx, wz):
            cx = math.floor(wx / 16.0)
            cz = math.floor(wz / 16.0)
            lx = wx - (cx * 16)
            lz = wz - (cz * 16)
            return (cx, cz), (lx, lz)

        # Inside origin chunk
        (cx, cz), (lx, lz) = world_to_chunk(5, 10)
        self.assertEqual((cx, cz), (0, 0))
        self.assertEqual((lx, lz), (5, 10))

        # Boundary coordinate
        (cx, cz), (lx, lz) = world_to_chunk(16, 32)
        self.assertEqual((cx, cz), (1, 2))
        self.assertEqual((lx, lz), (0, 0))

        # Negative coordinate
        (cx, cz), (lx, lz) = world_to_chunk(-1, -1)
        self.assertEqual((cx, cz), (-1, -1))
        self.assertEqual((lx, lz), (15, 15))

    def test_all_14_blender_glb_assets_exist_and_valid(self):
        """Verify all 17 low-poly 3D assets generated by headless Blender 5.2."""
        expected_assets = [
            "pickaxe.glb",
            "axe.glb",
            "sword.glb",
            "workbench.glb",
            "campfire.glb",
            "crate.glb",
            "citizen.glb",
            "furnace.glb",
            "support_beam.glb",
            "bandit.glb",
            "caravan_cart.glb",
            "hunting_bow.glb",
            "arrow.glb",
            "watchtower.glb",
            "enchanter_table.glb",
            "bandit_warlord.glb",
            "runestone.glb"
        ]

        for asset in expected_assets:
            path = os.path.join(self.models_dir, asset)
            self.assertTrue(os.path.exists(path), f"Asset {asset} missing!")
            self.assertGreater(os.path.getsize(path), 1000, f"Asset {asset} has suspiciously small size!")
            
            # Verify GLB magic header
            with open(path, "rb") as f:
                magic = f.read(4)
                self.assertEqual(magic, b"glTF", f"Asset {asset} does not have valid glTF magic header!")

    def test_single_persistent_monarch_paradigm(self):
        """Verify Single Persistent Monarch respawn and lack of dynasty succession."""
        player_health = 0.0
        respawn_hearth = (32.0, 25.0, 32.0)
        
        # When health reaches 0, monarch respawns at castle hearth
        if player_health <= 0:
            player_health = 50.0 # Heals in infirmary
            current_pos = respawn_hearth
            has_dynasty_succession = False
            has_permadeath = False
            realm_persists = True

        self.assertEqual(player_health, 50.0)
        self.assertEqual(current_pos, (32.0, 25.0, 32.0))
        self.assertFalse(has_dynasty_succession)
        self.assertFalse(has_permadeath)
        self.assertTrue(realm_persists)

    def test_supply_chain_production_cycle(self):
        """Verify resource balance in supply chain calculations."""
        inventory = {
            "wheat": 20,
            "bread": 50,
            "logs": 30,
            "stone": 25,
            "iron_ore": 10,
            "tools": 10
        }
        assigned = {
            "farmer": 2,
            "baker": 1,
            "lumberjack": 2,
            "miner": 1
        }
        
        # 1. Farmers produce 4 wheat per farmer
        wheat_prod = assigned["farmer"] * 4
        inventory["wheat"] += wheat_prod
        
        # 2. Baker consumes up to 2 wheat to produce 4 bread
        wheat_needed = assigned["baker"] * 2
        wheat_used = min(inventory["wheat"], wheat_needed)
        inventory["wheat"] -= wheat_used
        inventory["bread"] += wheat_used * 2
        
        # 3. Citizens consume 1 bread each
        total_citizens = sum(assigned.values())
        bread_eaten = min(inventory["bread"], total_citizens)
        inventory["bread"] -= bread_eaten
        
        self.assertEqual(inventory["wheat"], 26) # 20 + 8 - 2 = 26
        self.assertEqual(inventory["bread"], 48) # 50 + 4 - 6 = 48
        self.assertGreater(inventory["bread"], 0)

    def test_3d_pathfinder_step_rules(self):
        """Verify 3D grid pathfinding step-up (1m) and drop (2m) constraints."""
        max_step_up = 1
        max_safe_drop = 2
        
        # Valid moves
        self.assertTrue(1 <= max_step_up)
        self.assertTrue(2 <= max_safe_drop)
        # Invalid moves
        self.assertFalse(2 <= max_step_up) # Cannot climb 2m vertical cliff without ladder
        self.assertFalse(3 <= max_safe_drop) # 3m fall causes injury

    def test_workstation_recipes_and_crafting_costs(self):
        """Verify blueprint recipes, cost consumption, and result outputs."""
        inventory = {"logs": 10, "stone": 20, "iron_ore": 6, "wheat": 6}

        # Craft Iron Pickaxe: cost 3 iron_ore, 1 log
        req_iron = 3
        req_log = 1
        self.assertGreaterEqual(inventory["iron_ore"], req_iron)
        self.assertGreaterEqual(inventory["logs"], req_log)

        inventory["iron_ore"] -= req_iron
        inventory["logs"] -= req_log
        crafted_item = {"name": "Iron Pickaxe", "type": "tool", "count": 1}

        self.assertEqual(inventory["iron_ore"], 3)
        self.assertEqual(inventory["logs"], 9)
        self.assertEqual(crafted_item["name"], "Iron Pickaxe")

    def test_farmland_tilling_mechanic(self):
        """Verify grass/dirt conversion to farmland via hoe."""
        BLOCK_GRASS = 2
        BLOCK_DIRT = 1
        BLOCK_FARMLAND = 13
        BLOCK_WHEAT_CROP = 14

        # Till grass
        current_block = BLOCK_GRASS
        if current_block in [BLOCK_GRASS, BLOCK_DIRT]:
            new_block = BLOCK_FARMLAND
        self.assertEqual(new_block, BLOCK_FARMLAND)

        # Plant wheat on farmland
        if new_block == BLOCK_FARMLAND:
            crop_block = BLOCK_WHEAT_CROP
        self.assertEqual(crop_block, BLOCK_WHEAT_CROP)

    def test_agriculture_hydration_and_growth_ticks(self):
        """Verify soil hydration radius, 2.2x speed boost, and 3-stage maturity."""
        hydration_radius = 4
        # Test water proximity
        water_pos = (30, 20, 30)
        farmland_pos_hydrated = (32, 20, 32)
        farmland_pos_dry = (40, 20, 40)
        
        dx = abs(farmland_pos_hydrated[0] - water_pos[0])
        dz = abs(farmland_pos_hydrated[2] - water_pos[2])
        is_hydrated = dx <= hydration_radius and dz <= hydration_radius
        self.assertTrue(is_hydrated)
        
        dx_dry = abs(farmland_pos_dry[0] - water_pos[0])
        self.assertFalse(dx_dry <= hydration_radius)

        # Growth simulation
        base_duration = 18.0
        # Dry crop
        dry_progress = (18.0 / base_duration) * 1.0 # 1.0 = 100%
        # Hydrated crop grows 2.2x faster
        hydrated_progress = (8.18 / base_duration) * 2.2 # reaches ~1.0 in ~8.2s
        self.assertGreaterEqual(dry_progress, 1.0)
        self.assertGreaterEqual(hydrated_progress, 0.99)

        # Harvest yield
        harvest_yield = {"wheat": 3, "seeds": 2}
        self.assertEqual(harvest_yield["wheat"], 3)
        self.assertEqual(harvest_yield["seeds"], 2)

    def test_threat_formula_scaling_and_raid_composition(self):
        """Verify GDD Threat calculation: 10 + (Pop * 1.5) + (StockpileValue * 0.05)."""
        pop = 6
        stockpile_val = 120.0
        threat_score = 10.0 + (pop * 1.5) + (stockpile_val * 0.05)
        self.assertAlmostEqual(threat_score, 25.0)

        # Bandit party size
        bandit_count = max(1, min(4, int(threat_score / 15.0)))
        self.assertEqual(bandit_count, 1)

        # Scaled kingdom with higher stockpile and pop
        big_pop = 20
        big_stockpile = 800.0
        big_threat = 10.0 + (big_pop * 1.5) + (big_stockpile * 0.05) # 10 + 30 + 40 = 80
        big_bandit_count = max(1, min(4, int(big_threat / 15.0)))
        self.assertEqual(big_bandit_count, 4)

    def test_bandit_combat_mechanics_and_loot(self):
        """Verify bandit raider stats, melee damage, and loot drop on defeat."""
        bandit_hp = 60.0
        sword_damage = 35.0
        axe_damage = 24.0

        # Player hits with sword
        bandit_hp -= sword_damage
        self.assertEqual(bandit_hp, 25.0)
        # Player hits with axe
        bandit_hp -= axe_damage
        self.assertEqual(bandit_hp, 1.0)
        # Final strike
        bandit_hp -= 16.0 # pickaxe
        self.assertLessEqual(bandit_hp, 0.0)

        # Defeated raider drops loot
        loot = {"iron_ore": 1, "coins": 5, "bread": 1}
        self.assertIn("iron_ore", loot)
        self.assertIn("coins", loot)
        self.assertGreater(loot["coins"], 0)

    def test_torch_lighting_flicker_simulation(self):
        """Verify torch light parameters and flicker energy range."""
        base_energy = 1.8
        flicker_speed = 12.0
        time_sec = 1.5
        flicker = math.sin(time_sec * flicker_speed) * 0.15 + math.cos(time_sec * flicker_speed * 1.7) * 0.1
        current_energy = base_energy + flicker
        self.assertGreaterEqual(current_energy, 1.55)
        self.assertLessEqual(current_energy, 2.05)

    def test_geological_strata_depth_layers(self):
        """Verify depth distribution bounds for all ores in underground strata."""
        def get_expected_ore(ly, noise_val):
            if ly < 5 and noise_val > 0.48:
                return "DEEP_GEM_ORE"
            elif ly < 8 and noise_val > 0.42:
                return "GOLD_ORE"
            elif ly < 15 and noise_val > 0.35:
                return "IRON_ORE"
            elif ly < 20 and noise_val > 0.30:
                return "COPPER_ORE"
            elif ly < 25 and noise_val > 0.25:
                return "COAL_ORE"
            return "STONE"

        # Abyss level (ly = 3)
        self.assertEqual(get_expected_ore(3, 0.55), "DEEP_GEM_ORE")
        # Gold depth (ly = 7)
        self.assertEqual(get_expected_ore(7, 0.45), "GOLD_ORE")
        # Iron depth (ly = 12)
        self.assertEqual(get_expected_ore(12, 0.38), "IRON_ORE")
        # Copper depth (ly = 18)
        self.assertEqual(get_expected_ore(18, 0.32), "COPPER_ORE")
        # Coal depth (ly = 23)
        self.assertEqual(get_expected_ore(23, 0.28), "COAL_ORE")
        # Low noise stone default
        self.assertEqual(get_expected_ore(12, 0.10), "STONE")

    def test_smelting_furnace_recipes_and_stoichiometry(self):
        """Verify smelting furnace recipes, fuel combustion, and ingot yields."""
        inventory = {
            "iron_ore": 4,
            "copper_ore": 2,
            "gold_ore": 2,
            "coal": 10,
            "stone": 8,
            "iron_ingots": 0,
            "copper_ingot": 0,
            "gold_ingots": 0,
            "stone_bricks": 0
        }

        # Smelt 2 Iron Ingots (2 iron ore + 2 coal -> 2 iron ingots)
        iron_smelt_count = 2
        req_ore = iron_smelt_count * 1
        req_coal = iron_smelt_count * 1
        self.assertGreaterEqual(inventory["iron_ore"], req_ore)
        self.assertGreaterEqual(inventory["coal"], req_coal)
        inventory["iron_ore"] -= req_ore
        inventory["coal"] -= req_coal
        inventory["iron_ingots"] += iron_smelt_count

        self.assertEqual(inventory["iron_ingots"], 2)
        self.assertEqual(inventory["iron_ore"], 2)
        self.assertEqual(inventory["coal"], 8)

        # Bake 4 Stone Bricks (4 stone + 1 coal -> 4 stone bricks)
        inventory["stone"] -= 4
        inventory["coal"] -= 1
        inventory["stone_bricks"] += 4
        self.assertEqual(inventory["stone_bricks"], 4)
        self.assertEqual(inventory["stone"], 4)
        self.assertEqual(inventory["coal"], 7)

    def test_mine_support_beam_and_structural_integrity(self):
        """Verify structural stability radius (4 blocks) for supported mine ceilings."""
        support_beam_pos = (20, 10, 20)
        support_radius = 4

        # Block within support umbrella
        near_ceiling = (22, 12, 22)
        dist = max(abs(near_ceiling[0] - support_beam_pos[0]), abs(near_ceiling[2] - support_beam_pos[2]))
        is_supported = dist <= support_radius
        self.assertTrue(is_supported)

        # Block outside support umbrella
        far_ceiling = (26, 12, 20)
        dist_far = max(abs(far_ceiling[0] - support_beam_pos[0]), abs(far_ceiling[2] - support_beam_pos[2]))
        self.assertFalse(dist_far <= support_radius)

    def test_season_manager_cycle_and_temperatures(self):
        """Verify 4-season cycle, diurnal fluctuation, and weather temperature offsets."""
        base_temps = {
            "SPRING": 16.0,
            "SUMMER": 28.0,
            "AUTUMN": 11.0,
            "WINTER": -6.0
        }
        weather_mods = {
            "CLEAR": 0.0,
            "RAIN": -4.0,
            "THUNDERSTORM": -6.0,
            "SNOW": -8.0
        }

        # Calculate Midday Spring Clear (progress = 0.5)
        # sin((0.5 - 0.25) * 2pi) = sin(pi/2) = 1.0 => +5°C
        diurnal_midday = math.sin((0.5 - 0.25) * 2.0 * math.pi) * 5.0
        self.assertAlmostEqual(diurnal_midday, 5.0, places=3)
        temp_spring_noon = base_temps["SPRING"] + diurnal_midday + weather_mods["CLEAR"]
        self.assertAlmostEqual(temp_spring_noon, 21.0, places=3)

        # Calculate Midnight Winter Blizzard (progress = 0.0, weather = SNOW)
        # sin((0.0 - 0.25) * 2pi) = sin(-pi/2) = -1.0 => -5°C
        diurnal_midnight = math.sin((0.0 - 0.25) * 2.0 * math.pi) * 5.0
        self.assertAlmostEqual(diurnal_midnight, -5.0, places=3)
        temp_winter_blizzard = base_temps["WINTER"] + diurnal_midnight + weather_mods["SNOW"]
        self.assertAlmostEqual(temp_winter_blizzard, -19.0, places=3)

    def test_rain_and_thunderstorm_crop_hydration(self):
        """Verify rain hydration automates soil moisture for all agricultural crops."""
        crops = {
            (10, 15, 10): {"hydrated": False, "stage": 1},
            (11, 15, 10): {"hydrated": False, "stage": 2},
            (12, 15, 10): {"hydrated": True, "stage": 3}
        }
        
        # Simulate rain event
        for pos in crops:
            crops[pos]["hydrated"] = True

        for pos, data in crops.items():
            self.assertTrue(data["hydrated"], f"Crop at {pos} should be hydrated by rainfall!")

    def test_player_warmth_vitals_and_shelter_mechanics(self):
        """Verify warmth loss in freezing conditions, heat source protection, and ceiling shelter."""
        # Unprotected player in freezing temperature (-10°C)
        warmth = 100.0
        ambient_temp = -10.0
        is_sheltered = False
        near_heat_source = False
        delta = 1.0

        # Thermal decay rate
        def update_warmth(w, temp, sheltered, heat, dt):
            if heat:
                return min(100.0, w + 15.0 * dt)
            elif sheltered:
                if temp < 5.0:
                    return max(0.0, w - 0.8 * dt)
                return w
            else:
                if temp < 0.0:
                    chill = (0.0 - temp) * 0.4
                    return max(0.0, w - chill * dt)
                elif temp < 10.0:
                    return max(0.0, w - 0.5 * dt)
                return min(100.0, w + 2.0 * dt)

        # 5 seconds exposed in -10°C
        for _ in range(5):
            warmth = update_warmth(warmth, ambient_temp, is_sheltered, near_heat_source, delta)
        self.assertAlmostEqual(warmth, 80.0, places=1) # 100 - (10 * 0.4 * 5) = 80

        # Moving near a Campfire or Furnace restores warmth quickly
        near_heat_source = True
        for _ in range(2):
            warmth = update_warmth(warmth, ambient_temp, is_sheltered, near_heat_source, delta)
        self.assertAlmostEqual(warmth, 100.0, places=1) # 80 + 30 = 110 capped at 100

    def test_trade_caravan_exotic_wares_and_barter(self):
        """Verify trade caravan stock purchasing and surplus commodity selling."""
        inventory = {
            "coins": 30,
            "spices": 0,
            "bread": 10,
            "stone": 20
        }
        wares = {
            "spices": {"price": 12, "stock": 5},
            "fine_fabric": {"price": 15, "stock": 6}
        }
        purchase_rates = {
            "bread": 2,
            "stone": 1
        }

        # 1. Buy 2 spices (12 coins each = 24 coins)
        price = wares["spices"]["price"]
        for _ in range(2):
            self.assertGreaterEqual(inventory["coins"], price)
            self.assertGreater(wares["spices"]["stock"], 0)
            inventory["coins"] -= price
            inventory["spices"] += 1
            wares["spices"]["stock"] -= 1

        self.assertEqual(inventory["coins"], 6)
        self.assertEqual(inventory["spices"], 2)
        self.assertEqual(wares["spices"]["stock"], 3)

        # 2. Sell 5 bread to caravan (rate 2 coins/bread = 10 coins earned)
        sell_amount = 5
        self.assertGreaterEqual(inventory["bread"], sell_amount)
        inventory["bread"] -= sell_amount
        inventory["coins"] += purchase_rates["bread"] * sell_amount

        self.assertEqual(inventory["bread"], 5)
        self.assertEqual(inventory["coins"], 16)

    def test_arrow_ballistic_flight_and_parabolic_trajectory(self):
        """Verify arrow physics: horizontal velocity, gravity integration, and drop distance."""
        speed = 36.0 # m/s
        gravity = 9.8 # m/s^2
        angle_deg = 15.0 # shot at 15 degree angle
        angle_rad = math.radians(angle_deg)
        
        vx = speed * math.cos(angle_rad)
        vy = speed * math.sin(angle_rad)
        
        # Flight time to travel 25 meters horizontally: t = d / vx
        t_25m = 25.0 / vx
        self.assertAlmostEqual(t_25m, 0.719, places=2)
        
        # Height at 25m: y(t) = y0 + vy*t - 0.5*g*t^2
        y0 = 1.6 # monarch eye height
        y_at_25m = y0 + (vy * t_25m) - (0.5 * gravity * (t_25m ** 2))
        # Arrow should still be above ground
        self.assertGreater(y_at_25m, 0.0)
        self.assertAlmostEqual(y_at_25m, 5.86, delta=0.5)

    def test_guard_watchtower_elevation_bonus(self):
        """Verify +25% detection range and +15% kinetic damage multiplier from watchtowers."""
        base_range = 24.0
        base_damage = 30.0
        
        range_bonus_mult = 1.25
        damage_bonus_mult = 1.15
        
        watchtower_range = base_range * range_bonus_mult
        watchtower_damage = base_damage * damage_bonus_mult
        
        self.assertEqual(watchtower_range, 30.0)
        self.assertEqual(watchtower_damage, 34.5)
        
        # Target at 28 meters: out of ground range, but within watchtower range
        target_dist = 28.0
        self.assertFalse(target_dist <= base_range)
        self.assertTrue(target_dist <= watchtower_range)

    def test_fortification_durability_and_block_types(self):
        """Verify fortification block hardness and structural protection metrics."""
        hardness_table = {
            "WOODEN_PALISADE": 2.5,
            "STONE_BATTLEMENT": 3.0,
            "WOODEN_GATE": 1.8
        }
        
        # Stone battlements resist siege attacks better than wood palisades
        self.assertGreater(hardness_table["STONE_BATTLEMENT"], hardness_table["WOODEN_PALISADE"])
        # Palisades resist axe/sword strikes better than normal wood (1.0)
        self.assertGreater(hardness_table["WOODEN_PALISADE"], 1.0)
        # Gate has moderate hardness to allow player pass-through
        self.assertEqual(hardness_table["WOODEN_GATE"], 1.8)

    def test_enchantment_sharpness_and_power_scaling(self):
        """Verify Sharpness melee bonus and Power ranged velocity & damage formulas."""
        base_melee = 35.0 # Knight Sword base
        
        # Tier 1 (+15% -> 40.25)
        t1_melee = base_melee * (1.0 + 1 * 0.15)
        self.assertAlmostEqual(t1_melee, 40.25)
        
        # Tier 5 (+75% -> 61.25)
        t5_melee = base_melee * (1.0 + 5 * 0.15)
        self.assertAlmostEqual(t5_melee, 61.25)

        base_arrow = 45.0
        # Power Tier 3 (+45% -> 65.25)
        t3_arrow = base_arrow * (1.0 + 3 * 0.15)
        self.assertAlmostEqual(t3_arrow, 65.25)

    def test_vampiric_leech_life_steal_calculation(self):
        """Verify 15% life steal absorption into monarch health."""
        damage_dealt = 40.0
        life_steal_ratio = 0.15
        healed_hp = damage_dealt * life_steal_ratio
        self.assertEqual(healed_hp, 6.0)

        monarch_hp = 50.0
        max_hp = 100.0
        new_hp = min(max_hp, monarch_hp + healed_hp)
        self.assertEqual(new_hp, 56.0)

    def test_dragons_breath_combustion_damage(self):
        """Verify Dragon's Breath burning duration and tick damage."""
        burn_duration = 4.0 # seconds
        burn_dps = 8.0 # dmg / sec
        total_burn_damage = burn_duration * burn_dps
        self.assertEqual(total_burn_damage, 32.0)

    def test_bandit_warlord_stats_and_guaranteed_affix_drop(self):
        """Verify Bandit Warlord boss characteristics and guaranteed legendary loot table."""
        warlord_hp = 160.0
        warlord_dmg = 26.0
        legendary_runes = [
            "dragons_breath",
            "vampiric_leech",
            "thunderstrike",
            "windstrider",
            "fortress_heart"
        ]
        
        self.assertGreaterEqual(warlord_hp, 150.0)
        self.assertGreaterEqual(warlord_dmg, 25.0)
        self.assertEqual(len(legendary_runes), 5)
        self.assertIn("dragons_breath", legendary_runes)
        self.assertIn("vampiric_leech", legendary_runes)

    def test_fortress_heart_barrier_activation(self):
        """Verify 90% mitigation shield activation when monarch HP falls below 25%."""
        max_hp = 100.0
        low_hp = 20.0 # 20% < 25% threshold
        incoming_attack = 50.0
        
        # When under 25% HP, Fortress Heart triggers
        is_triggered = low_hp < (max_hp * 0.25)
        self.assertTrue(is_triggered)
        mitigated_damage = incoming_attack * 0.1 # 90% reduction
        self.assertEqual(mitigated_damage, 5.0)

if __name__ == "__main__":
    unittest.main()
